# Generated by Django 6.0.4 on 2026-04-24 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_appointment_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="PharmacyStock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=255, unique=True)),
                ("dosage", models.CharField(max_length=100)),
                ("quantity_available", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("supplier", models.CharField(blank=True, max_length=255)),
                ("last_restocked", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="LabTest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=255)),
                ("test_type", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("ordered_at", models.DateTimeField(auto_now_add=True)),
                ("expected_completion", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ordered", "Ordered"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="ordered",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ordered_tests",
                        to="core.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lab_tests",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-ordered_at"],
            },
        ),
        migrations.CreateModel(
            name="LabResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("result_value", models.TextField()),
                ("reference_range", models.CharField(blank=True, max_length=255)),
                ("notes", models.TextField(blank=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("technician_name", models.CharField(blank=True, max_length=255)),
                (
                    "lab_test",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="core.labtest",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Prescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="core.doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.hospital"
                    ),
                ),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prescriptions",
                        to="core.patient",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PrescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drug_name", models.CharField(max_length=255)),
                ("dosage", models.CharField(max_length=100)),
                ("frequency", models.CharField(max_length=100)),
                ("duration", models.CharField(max_length=100)),
                ("quantity", models.IntegerField()),
                ("instructions", models.TextField(blank=True)),
                (
                    "prescription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="core.prescription",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PharmacyDispensing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_dispensed", models.IntegerField()),
                ("dispensed_at", models.DateTimeField(auto_now_add=True)),
                ("dispensed_by", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("dispensed", "Dispensed"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("receipt_number", models.CharField(max_length=100, unique=True)),
                (
                    "pharmacy_stock",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.pharmacystock",
                    ),
                ),
                (
                    "prescription_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.prescriptionitem",
                    ),
                ),
            ],
        ),
    ]
